export const phones = [
  {
    id: 1,
    phoneName: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 34900,
    launchPrice: 43164,
    storage: "256GB",
    ram: "8GB",
    battery: "4422mAh",
    camera: "48MP + 12MP + 12MP",
    screenSize: 6.7,
    os: "iOS 17",
    releaseYear: 2023,
    rating: 4,
    inStock: true,
    description:
      "Apple’s flagship phone with the A17 Pro chip, titanium frame, and 48MP main camera offering outstanding performance and battery life."
  },
  {
    id: 2,
    phoneName: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 30900,
    launchPrice: 46764,
    storage: "512GB",
    ram: "12GB",
    battery: "5000mAh",
    camera: "200MP + 12MP + 10MP + 10MP",
    screenSize: 6.8,
    os: "Android 14",
    releaseYear: 2024,
    rating: 5,
    inStock: true,
    description:
      "The most advanced Galaxy yet with an ultra-clear 200MP camera, S-Pen support, and Snapdragon 8 Gen 3 processor."
  },
  {
    id: 3,
    phoneName: "Google Pixel 8 Pro",
    brand: "Google",
    price: 13732,
    launchPrice: 35964,
    storage: "256GB",
    ram: "12GB",
    battery: "5050mAh",
    camera: "50MP + 48MP + 48MP",
    screenSize: 6.7,
    os: "Android 14",
    releaseYear: 2023,
    rating: 5,
    inStock: true,
    description:
      "Google’s top-tier AI-powered smartphone with Tensor G3, best-in-class camera software, and long software support."
  },
  {
    id: 4,
    phoneName: "OnePlus 12",
    brand: "OnePlus",
    price: 18949,
    launchPrice: 32364,
    storage: "256GB",
    ram: "16GB",
    battery: "5400mAh",
    camera: "50MP + 48MP + 64MP",
    screenSize: 6.82,
    os: "Android 14 (OxygenOS)",
    releaseYear: 2024,
    rating: 5,
    inStock: false,
    description:
      "High-performance flagship with smooth OxygenOS, powerful Snapdragon 8 Gen 3, and a large battery."
  },
  {
    id: 5,
    phoneName: "Xiaomi 14 Pro",
    brand: "Xiaomi",
    price: 15990,
    launchPrice: 28764,
    storage: "256GB",
    ram: "12GB",
    battery: "4880mAh",
    camera: "50MP + 50MP + 50MP",
    screenSize: 6.73,
    os: "Android 14 (HyperOS)",
    releaseYear: 2024,
    rating: 3,
    inStock: true,
    description:
      "Compact and fast flagship featuring Leica-powered cameras and Xiaomi’s new HyperOS system."
  },
  {
    id: 6,
    phoneName: "ASUS ROG Phone 8 Pro",
    brand: "ASUS",
    price: 23990,
    launchPrice: 39564,
    storage: "512GB",
    ram: "16GB",
    battery: "5500mAh",
    camera: "50MP + 13MP + 32MP",
    screenSize: 6.78,
    os: "Android 14",
    releaseYear: 2024,
    rating: 3,
    inStock: true,
    description:
      "A gaming powerhouse with Snapdragon 8 Gen 3, AirTrigger controls, and a massive cooling system."
  },
  {
    id: 7,
    phoneName: "Sony Xperia 1 V",
    brand: "Sony",
    price: 9674,
    launchPrice: 43164,
    storage: "256GB",
    ram: "12GB",
    battery: "5000mAh",
    camera: "48MP + 12MP + 12MP",
    screenSize: 6.5,
    os: "Android 13",
    releaseYear: 2023,
    rating: 4,
    inStock: true,
    description:
      "Sony’s camera-focused smartphone designed for photographers with real-time tracking and 4K display."
  },
  {
    id: 8,
    phoneName: "Oppo Find X7 Ultra",
    brand: "Oppo",
    price: 16999,
    launchPrice: 35964,
    storage: "512GB",
    ram: "16GB",
    battery: "5000mAh",
    camera: "50MP + 50MP + 50MP + 50MP",
    screenSize: 6.82,
    os: "Android 14 (ColorOS)",
    releaseYear: 2024,
    rating: 2,
    inStock: true,
    description:
      "Premium flagship with four 50MP cameras and the world’s first dual periscope zoom setup."
  },
  {
    id: 9,
    phoneName: "Realme GT 5 Pro",
    brand: "Realme",
    price: 15990,
    launchPrice: 26964,
    storage: "256GB",
    ram: "12GB",
    battery: "5400mAh",
    camera: "50MP + 8MP + 50MP",
    screenSize: 6.78,
    os: "Android 14",
    releaseYear: 2024,
    rating: 2,
    inStock: true,
    description:
      "Affordable flagship killer with Snapdragon 8 Gen 3, fast 100W charging, and vibrant AMOLED display."
  },
  {
    id: 10,
    phoneName: "Vivo X100 Pro",
    brand: "Vivo",
    price: 18039,
    launchPrice: 39564,
    storage: "512GB",
    ram: "16GB",
    battery: "5400mAh",
    camera: "50MP + 50MP + 64MP",
    screenSize: 6.78,
    os: "Android 14 (FuntouchOS)",
    releaseYear: 2024,
    rating: 1,
    inStock: true,
    description:
      "Co-engineered with Zeiss, offering superb low-light photography and top-tier performance."
  },
  {
    id: 11,
    phoneName: "iPhone 14",
    brand: "Apple",
    price: 17500,
    launchPrice: 28764,
    storage: "128GB",
    ram: "6GB",
    battery: "3279mAh",
    camera: "12MP + 12MP",
    screenSize: 6.1,
    os: "iOS 16",
    releaseYear: 2022,
    rating: 5,
    inStock: true,
    description:
      "Apple’s 2022 flagship with A15 Bionic chip and a reliable dual-camera system."
  },
  {
    id: 12,
    phoneName: "Samsung Galaxy A54",
    brand: "Samsung",
    price: 12999,
    launchPrice: 16164,
    storage: "128GB",
    ram: "8GB",
    battery: "5000mAh",
    camera: "50MP + 12MP + 5MP",
    screenSize: 6.4,
    os: "Android 13",
    releaseYear: 2023,
    rating: 3,
    inStock: true,
    description:
      "A midrange phone with premium design, Super AMOLED screen, and long-lasting battery life."
  },
  {
    id: 13,
    phoneName: "Nothing Phone (2)",
    brand: "Nothing",
    price: 15674,
    launchPrice: 25164,
    storage: "256GB",
    ram: "12GB",
    battery: "4700mAh",
    camera: "50MP + 50MP",
    screenSize: 6.7,
    os: "Android 13 (Nothing OS)",
    releaseYear: 2023,
    rating: 3,
    inStock: true,
    description:
      "A unique transparent design phone offering clean Android experience and eye-catching LED Glyph interface."
  },
  {
    id: 14,
    phoneName: "Motorola Edge 40 Pro",
    brand: "Motorola",
    price: 13904,
    launchPrice: 32364,
    storage: "256GB",
    ram: "12GB",
    battery: "4600mAh",
    camera: "50MP + 50MP + 12MP",
    screenSize: 6.67,
    os: "Android 13",
    releaseYear: 2023,
    rating: 0,
    inStock: false,
    description:
      "Sleek design with 165Hz display, Snapdragon 8 Gen 2, and ultra-fast 125W wired charging."
  },
  {
    id: 15,
    phoneName: "Honor Magic6 Pro",
    brand: "Honor",
    price: 34990,
    launchPrice: 39564,
    storage: "512GB",
    ram: "16GB",
    battery: "5600mAh",
    camera: "50MP + 50MP + 180MP",
    screenSize: 6.8,
    os: "Android 14 (MagicOS)",
    releaseYear: 2024,
    rating: 4.5,
    inStock: true,
    description:
      "A premium device with cutting-edge camera hardware and impressive display technology."
  },
  {
    id: 16,
    phoneName: "Poco F5 Pro",
    brand: "Poco",
    price: 8799,
    launchPrice: 19764,
    storage: "256GB",
    ram: "12GB",
    battery: "5160mAh",
    camera: "64MP + 8MP + 2MP",
    screenSize: 6.67,
    os: "Android 13 (MIUI)",
    releaseYear: 2023,
    rating: 4.1,
    inStock: true,
    description:
      "Value-for-money flagship killer with Snapdragon 8+ Gen 1 and smooth 120Hz AMOLED display."
  },
  {
    id: 17,
    phoneName: "Redmi Note 13 Pro+",
    brand: "Xiaomi",
    price: 9499,
    launchPrice: 17964,
    storage: "256GB",
    ram: "12GB",
    battery: "5000mAh",
    camera: "200MP + 8MP + 2MP",
    screenSize: 6.67,
    os: "Android 14 (MIUI)",
    releaseYear: 2024,
    rating: 4.3,
    inStock: true,
    description:
      "Affordable device featuring a 200MP camera, curved OLED display, and fast 120W charging."
  },
  {
    id: 18,
    phoneName: "Infinix Zero Ultra",
    brand: "Infinix",
    price: 9499,
    launchPrice: 17964,
    storage: "256GB",
    ram: "8GB",
    battery: "4500mAh",
    camera: "200MP + 13MP + 2MP",
    screenSize: 6.8,
    os: "Android 12",
    releaseYear: 2023,
    rating: 4.0,
    inStock: false,
    description:
      "Midrange phone offering a 200MP camera and ultra-fast 180W charging at an affordable price."
  },
  {
    id: 19,
    phoneName: "Realme Narzo 70 Pro",
    brand: "Realme",
    price: 9499,
    launchPrice: 12564,
    storage: "128GB",
    ram: "8GB",
    battery: "5000mAh",
    camera: "50MP + 2MP + 2MP",
    screenSize: 6.6,
    os: "Android 14",
    releaseYear: 2024,
    rating: 4.1,
    inStock: true,
    description:
      "Budget smartphone with good battery life, smooth display, and modern design for everyday use."
  },
  {
    id: 20,
    phoneName: "Tecno Phantom X2 Pro",
    brand: "Tecno",
    price: 9499,
    launchPrice: 25164,
    storage: "256GB",
    ram: "12GB",
    battery: "5160mAh",
    camera: "50MP + 50MP + 13MP",
    screenSize: 6.8,
    os: "Android 13 (HiOS)",
    releaseYear: 2023,
    rating: 4.2,
    inStock: true,
    description:
      "Stylish premium midrange with retractable portrait camera and curved AMOLED screen."
  }
];
